import type { Publication } from './types';

// Source of truth: MERITOS.md, section 5 ("Publicaciones científicas (JCR / indexadas)").
// Only facts present there (or explicitly confirmed by Ángel) are encoded here —
// no DOI/author list is fabricated for entries where it isn't confirmed.
export const publications: Publication[] = [
  {
    id: 'pub1',
    type: 'article',
    year: 2026,
    yearLabel: 'In press',
    authors: 'Herrero, R.; Martínez-Sanchis, M.; Zamora, Á.; Vara, M.D.; Campos, D.; García-Campayo, J.; Baños, R.',
    title:
      'Internet-Based Attachment-Based Compassion Therapy for Adults With Chronic Medical Conditions: Randomized Controlled Trial',
    journal: 'Journal of Medical Internet Research (JMIR)',
    doi: 'http://dx.doi.org/10.2196/86679',
    quartile: 'Q1',
    position: '3/7',
    impactFactor: '8.2',
    firstAuthor: false,
    authorPosition: 3,
    totalAuthors: 7,
  },
  {
    id: 'pub2',
    type: 'article',
    year: 2026,
    authors:
      'García-Lucas, C.; Zamora, Á.; Amer-Cuenca, J.J.; Arguisuelas, M.D.; Pardo, J.; Baños, R.M.; Lisón, J.F.; Biviá-Roig, G.',
    title:
      'Effects of standard prenatal education with and without pain neuroscience education on functionality appreciation and body surveillance in pregnant women with lumbopelvic pain: a secondary analysis of a RCT',
    journal: 'Midwifery (Elsevier)',
    quartile: 'Q1',
    position: '2/8',
    impactFactor: '2.7',
    firstAuthor: false,
    authorPosition: 2,
    totalAuthors: 8,
  },
  {
    id: 'pub3',
    type: 'article',
    year: 2026,
    yearLabel: '2025/2026',
    authors: 'Corno, G.; Zamora, Á.; Bouchard, S.; Baños, R.M.; Baillot, A.; Monthuy-Blanc, J.',
    title:
      'Exploring Virtual Reality for Body Image Assessment and Psychological Interventions in Individuals with Obesity: A Comprehensive Review',
    journal: 'Obesity Reviews (Wiley)',
    quartile: 'Q1',
    position: '2/5',
    impactFactor: '7.6',
    firstAuthor: false,
    authorPosition: 2,
    totalAuthors: 5,
  },
  {
    id: 'pub4',
    type: 'article',
    year: 2026,
    authors: 'Navarro-Moreno, V.; Zamora, Á.; Herrero, R.; Miragall, M.; Parola, G.; Saccone, V.; Baños, R.M.',
    title:
      'Body image and body awareness interventions in chronic pain: A systematic review of effects on pain-related variables and emotional distress',
    journal: 'Journal of Pain Research (Dove Medical Press)',
    quartile: 'Q2',
    position: '2/7',
    impactFactor: '3.1',
    firstAuthor: false,
    authorPosition: 2,
    totalAuthors: 7,
  },
  {
    id: 'pub5',
    type: 'article',
    year: 2025,
    authors: 'Navarro-Moreno, V.; Herrero, R.; Zamora, Á.; Miragall, M.; Baños, R.M.',
    title: 'Enhancing Body Image in Chronic Pain: A Case Study Utilizing Virtual Reality',
    journal: 'Journal of Clinical Psychology (Wiley)',
    quartile: 'Q2',
    position: '3/5',
    impactFactor: '2.7',
    firstAuthor: false,
    authorPosition: 3,
    totalAuthors: 5,
  },
  {
    id: 'pub6',
    type: 'article',
    year: 2025,
    authors: 'Zamora, Á.; Parola, G.; Desdentado, L.; Herrero, R.; Miragall, M.; Baños, R.',
    title: 'Understanding the role of positive body image in chronic low back pain: A path-analytic model',
    journal: 'Body Image (Elsevier)',
    quartile: 'Q1',
    position: '1/6',
    impactFactor: '6.0',
    firstAuthor: true,
    authorPosition: 1,
    totalAuthors: 6,
  },
  {
    id: 'pub7',
    type: 'article',
    year: 2024,
    authors:
      'Pierantonelli, M.; Mira, A.; Zamora, Á.; Desdentado, L.; Diego-Pedro, R.; González-Hernández, E.; Bretón-López, J.; García-Palacios, A.; Baños, R.M.',
    title: 'Levels and Predictors of Suicide Literacy and Suicide Stigma in Spanish-Speaking Individuals',
    journal: 'Brain and Behavior (Wiley)',
    quartile: 'Q2',
    position: '3/9',
    impactFactor: '2.8',
    firstAuthor: false,
    authorPosition: 3,
    totalAuthors: 9,
  },
  {
    id: 'pub8',
    type: 'article',
    year: 2024,
    authors:
      'Pierantonelli, M.; Mira, A.; Martínez-Gregorio, S.; Zamora, Á.; Diego-Pedro, R.; Escrivá-Martínez, T.; Bretón-López, J.; García-Palacios, A.; Baños, R.M.',
    title:
      'Validation of three scales for enhanced suicide prevention in Spanish-speaking populations: Suicidal ideation, stigma, and literacy',
    journal: 'Journal of Psychiatric Research (Elsevier)',
    quartile: 'Q2',
    position: '4/9',
    impactFactor: '3.6',
    firstAuthor: false,
    authorPosition: 4,
    totalAuthors: 9,
  },
  {
    id: 'pub9',
    type: 'article',
    year: 2024,
    authors:
      'Mebarak, M.; Maïano, C.; Mendoza, J.; Zamora, Á.; Baños, R.; Desdentado, L.; Miragall, M.; Herrero, R.; Swami, V.',
    title:
      'Measurement invariance and differential item functioning of the Functionality Appreciation Scale (FAS) in Colombia and Spain',
    journal: 'Body Image (Elsevier)',
    quartile: 'Q1',
    position: '4/9',
    impactFactor: '6.0',
    firstAuthor: false,
    authorPosition: 4,
    totalAuthors: 9,
  },
  {
    id: 'pub10',
    type: 'article',
    year: 2024,
    authors: 'Zamora, Á.; Desdentado, L.; Herrero, R.; Miragall, M.; Baños, R.',
    title: 'Psychometric properties of the Spanish version of the Functionality Appreciation Scale',
    journal: 'Journal of Eating Disorders (Springer)',
    quartile: 'Q1',
    position: '1/5',
    impactFactor: '5.7',
    firstAuthor: true,
    authorPosition: 1,
    totalAuthors: 5,
  },
];
